const dbProductos = [
    {
        imagen: "../src/img/Ropa/chaqueta1.webp",
        nombre: "Chaqueta de cuero",
        color: "Negro",
        talla: "M",
        precio: 100,
        id: 1,
        data: "vestimentas a la moda ropa vetir 2020 2021 2022 2023 exclusivo chaquetas  de cuero de color negro talla m con precios de 100 soles",
    },
    {
        imagen: "../src/img/Ropa/chaqueta2.webp",
        nombre: "Chaqueta de mujer",
        color: "Azul",
        talla: "L",
        precio: 140,
        id: 2,
        data: "vestimentas a la moda ropa vetir 2020 2021 2022 2023 exclusivo chaquetas  de mujer de color azul talla l con precios de 140 soles",
    },
    {
        imagen: "../src/img/Ropa/chaqueta3.webp",
        nombre: "Abrigo con gorral",
        color: "Negro",
        talla: "S",
        precio: 200,
        id: 3,
        data: "vestimentas a la moda ropa vetir 2020 2021 2022 2023 exclusivo abrigos con gorrales de color negro talla s con precios de 200 soles",
    },
    {
        imagen: "../src/img/Ropa/chaqueta4.webp",
        nombre: "Chompa de Cuero",
        color: "Negro",
        talla: "S",
        precio: 230,
        id: 4,
        data: "vestimentas a la moda ropa chompas vetir vestirse 2020 2021 2022 2023 exclusivo chompa de cuero de color negro talla s con precios de 230 soles",
    },
    {
        imagen: "../src/img/Ropa/chaqueta5.webp",
        nombre: "Chompa de algodon",
        color: "Rojo",
        talla: "L",
        precio: 300,
        id: 5,
        data: "vestimentas a la moda ropa chompas vetir vestirse 2020 2021 2022 2023 exclusivo chompa de algodon de color rojo talla l con precios de 300 soles",
    },

    {
        imagen: "../src/img/Ropa/chaqueta6.webp",
        nombre: "Chompa 2020 para dama",
        color: "Negro",
        talla: "L",
        precio: 300,
        id: 6,
        data: "vestimentas a la moda ropa chompas vetir vestirse 2020 2021 2022 2023 exclusivo chompa 2020 para dama de color negro talla l con precios de 300 soles",
    },
    {
        imagen: "../src/img/Ropa/chaqueta7.webp",
        nombre: "Casaca de algodon",
        color: "Verde",
        talla: "S",
        precio: 210,
        id: 7,
        data: "vestimentas a la moda ropa vetir 2020 2021 2022 2023 exclusivo casaca de algodon de color verde talla s con precios de 210 soles",
    },
    {
        imagen: "../src/img/Ropa/chaqueta8.webp",
        nombre: "Abrigo de otoño",
        color: "Gris",
        talla: "M",
        precio: 200,
        id: 8,
        data: "vestimentas a la moda ropa vetir 2020 2021 2022 2023 exclusivo abrigos de otoño de color gris talla m con precios de 200 soles",
    },
    {
        imagen: "../src/img/Ropa/chaqueta9.webp",
        nombre: "Casaca de vertir",
        color: "Negro",
        talla: "M",
        precio: 200,
        id: 9,
        data: "vestimentas a la moda ropa vetir 2020 2021 2022 2023 exclusivo casaca de vertir de color negro talla m con precios de 200 soles",
    },
    {
        imagen: "../src/img/Ropa/chaqueta10.webp",
        nombre: "Camisa Mangalarga",
        color: "Gris",
        talla: "L",
        precio: 140,
        id: 10,
        data: "vestimentas a la moda ropa vetir 2020 2021 2022 2023 exclusivo camisa mangalarga de color gris talla l con precios de 140 soles",
    },
    {
        imagen: "../src/img/Ropa/chaqueta11.webp",
        nombre: "Casaca de invierno",
        color: "Azul",
        talla: "S",
        precio: 200,
        id: 11,
        data: "vestimentas a la moda ropa vetir 2020 2021 2022 2023 exclusivo casaca de invierno de color azul talla s con precios de 200 soles",
    },
    {
        imagen: "../src/img/Ropa/chaqueta12.webp",
        nombre: "Chaqueta de correr",
        color: "Azul",
        talla: "M",
        precio: 580,
        id: 12,
        data: "vestimentas a la moda ropa vetir 2020 2021 2022 2023 exclusivo chaquetas  de correr de color azul talla m con precios de 580 soles",
    },
    {
        imagen: "../src/img/Ropa/chaqueta13.webp",
        nombre: "Chaqueta exclusiva 2022",
        color: "Marron",
        talla: "M",
        precio: 700,
        id: 13,
        data: "vestimentas a la moda ropa vetir 2020 2021 2022 2023 exclusivo chaquetas  exclusiva 2022 de color marron talla m con precios de 700 soles",
    },
    {
        imagen: "../src/img/Ropa/chaqueta14.webp",
        nombre: "Chaqueta de ejercicio",
        color: "Celeste",
        talla: "L",
        precio: 800,
        id: 14,
        data: "vestimentas a la moda ropa vetir 2020 2021 2022 2023 exclusivo chaquetas  de ejercicio de color celeste talla l con precios de 800 soles",
    },
    {
        imagen: "../src/img/Ropa/chaqueta15.webp",
        nombre: "Casaca serie x-20",
        color: "Celeste",
        talla: "S",
        precio: 500,
        id: 15,
        data: "vestimentas a la moda ropa vetir 2020 2021 2022 2023 exclusivo casaca serie x-20 de color celeste talla s con precios de 500 soles",
    },
    {
        imagen: "../src/img/Ropa/chaqueta16.webp",
        nombre: "Casaca serie r-102",
        color: "Negro",
        talla: "M",
        precio: 760,
        id: 16,
        data: "vestimentas a la moda ropa vetir 2020 2021 2022 2023 exclusivo casaca serie r-102 de color negro talla m con precios de 760 soles",
    },
    {
        imagen: "../src/img/Ropa/chaqueta17.webp",
        nombre: "Abrigo de vestir",
        color: "Negro",
        talla: "L",
        precio: 400,
        id: 17,
        data: "vestimentas a la moda ropa vetir 2020 2021 2022 2023 exclusivo abrigos de vertir de color negro talla l con precios de 400 soles",
    },
    {
        imagen: "../src/img/Ropa/chaqueta18.webp",
        nombre: "Casaca de san valentin",
        color: "Rojo",
        talla: "S",
        precio: 200,
        id: 18,
        data: "vestimentas a la moda ropa vetir 2020 2021 2022 2023 exclusivo casaca de san valentin de color rojo talla s con precios de 200 soles",
    },
    {
        imagen: "../src/img/Ropa/chaqueta19.webp",
        nombre: "Chompa de colegio n-911",
        color: "Rojo",
        talla: "M",
        precio: 90,
        id: 19,
        data: "vestimentas a la moda ropa chompas vetir vestirse 2020 2021 2022 2023 exclusivo chompa de colegio n-911 de color rojo talla m con precios de 90 soles",
    },
    {
        imagen: "../src/img/Ropa/chaqueta20.webp",
        nombre: "Chaqueta para dama",
        color: "Azul",
        talla: "S",
        precio: 200,
        id: 20,
        data: "vestimentas a la moda ropa vetir 2020 2021 2022 2023 exclusivo chaquetas  para dama de color azul talla s con precios de 200 soles",
    },
];
